### ISSUE TITLE
Actual Luigi Difficulty. 

### ISSUE THREAD

**Issue by MadTurt1e** [MadTurt1e/PicturePoker#11]
Luigi should be able to enter a god-like state, and be able to change his cards and look at other people's cards, as this is the spirit of Luigi Poker. 

Also, Luigi should also be able to be somewhat good at the game, if need be.

**Comment by malek1038** [comment]
How about we limit the number of cards luigi can change depending on the difficulty, like on easy he only changes 1 card. And then on the hardest difficulty he could cheat, and have a chance of magically swapping to 4 or 5 stars or something like that

**Comment by MadTurt1e** [comment]
This sounds like an excellent idea

**Comment by jeffreyw2025** [comment]
Change of plans- We will no longer be making super Luigi AI. Just a regular AI will do.
