### ISSUE TITLE
Implement all 6 suits

### ISSUE THREAD

**Issue by MadTurt1e** [MadTurt1e/PicturePoker#2]
The suits are: 

- Star
- Mario
- Luigi
- Fire Flower
- Mushroom
- Cloud

This should be implemented in an database table (however one implements it)

**Comment by malek1038** [comment]
I am adding the card class with the suits, someone still needs to implement it as a database table

**Comment by jeffreyw2025** [comment]
I've been thinking about how to implement the cards database-wise. I'm planning to probably tie the Cards to the Players as a "weak entity" of sorts. I think in addition to the suits I will add a boolean to determine if the Card needs to be changed out and a number associated with the card's position in the hand.

**Comment by jeffreyw2025** [comment]
The suits have been implemented on the database side as suits.sql and as an enum in the Card class on the backend. That should be good enough for the time being.
