### ISSUE TITLE
Lobby and Main Menu

### ISSUE THREAD

**Issue by MadTurt1e** [MadTurt1e/PicturePoker#9]
This system is probably to be implemented at the end. 
We want a menu system, where the player can chose which lobby to go into, view statistics, the like. 
In addition, we want a lobby creation system (I am assuming this will be like Amogus), which has a few feature

- High Stakes / Low stakes betting: Players can choose how much the buy in price is. 
- Round Count - 3, 5, or 7. 11 if we're feeling lucky. 
Implementation of high/low stakes betting and round count should be assumed - ie, don't hard code these values. 

This is very much so a UI section, and as such, probably only needs implementation when we learn of UI and the like.

**Comment by jeffreyw2025** [comment]
Good to note that the stakes and round count would probably need to be tracked in the database system. I could probably handle that functionality.
